version: '3'
services:
  sleek-airflow:
    image: apache/airflow
    volumes:
      - /mnt/c/zdinosaur/volume-mount/docker-airflow-dags-simple:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
