apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: airflow-redis-worker-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Supported policies: Delete, Retain
reclaimPolicy: Retain
