apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-redis-worker-pv
  labels:
    vol-mount: airflow-redis-worker
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airflow-redis-worker-storage-class
  local:
    path: /mnt/c/zdinosaur/volume-mount/airflow-redis-worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bdc7-l-j9h1fx3
