apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: airflow-dags-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
# Supported policies: Delete, Retain
reclaimPolicy: Retain
